---
# tasks file for docker
- name: upgrade OS
  become: true
  apt:
      upgrade: full
      update_cache: yes
      cache_valid_time: 86400
      force_apt_get: True
- name: Install docker
  become: true
  apt:
    name: docker.io
- name: Ensure group "docker" exists
  group:
    name: docker
    state: present

- name: Add the user 'ubuntu' to 'docker group'
  become: true
  user:
    name: ubuntu
    group: docker
    append: yes

- name: kill all containers
  shell: docker kill $(docker ps  -q)
  ignore_errors: True

- name: clean stopped containers
  shell: docker container prune -f
  ignore_errors: True

- name: start sample container
  shell: docker run -d mkarakas/simple-rest
  ignore_errors: True
